name: "Documentation Issue 📚"
description: Report issues in our documentation
title: " "
labels:
  - documentation
  - backlog
assignees: " "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report! Before submitting, please make sure to [search through existing issues](https://github.com/Azure/data-product-streaming/issues) and [check the Known Issues section](/docs/EnterpriseScaleAnalytics-KnownIssues.md).

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      placeholder: Briefly describe which document needs to be corrected and why.
    validations:
      required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
