parameters:
  - name: environment_name
    displayName: Environment Name
    type: string
  - name: variable_group_name
    displayName: Variable Group Name
    type: string

jobs:
  - job: Deployment
    displayName: "Deployment to ${{ parameters.environment_name }}"
    continueOnError: false
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - group: ${{ parameters.variable_group_name }}

    steps:
      # Checkout code
      - checkout: self
        name: checkout_repository
        displayName: "Checkout repository"
        submodules: true
        lfs: false
        clean: true
        continueOnError: false
        enabled: true

      # Generate Password 001
      - task: PowerShell@2
        name: generate_password_001
        displayName: Generate Password 001
        enabled: true
        continueOnError: false
        inputs:
          targetType: "filePath"
          filePath: "$(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1"
          errorActionPreference: "stop"
          failOnStderr: false
          ignoreLASTEXITCODE: false
          pwsh: true

      # Deploy Data Product
      - task: AzureResourceManagerTemplateDeployment@3
        name: data_product_deployment
        displayName: Deploy Data Product
        enabled: true
        continueOnError: false
        inputs:
          deploymentScope: "Resource Group"
          azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
          subscriptionId: $(AZURE_SUBSCRIPTION_ID)
          action: "Create Or Update Resource Group"
          resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
          location: $(AZURE_LOCATION)
          templateLocation: "Linked artifact"
          csmFile: "$(System.DefaultWorkingDirectory)/infra/main.json"
          csmParametersFile: "$(System.DefaultWorkingDirectory)/infra/params.${{ parameters.environment_name }}.json"
          deploymentMode: "Incremental"
          overrideParameters: >
            -administratorPassword "$(password)"
