name: Data Product Deployment - Dev

on:
  push:
    branches: [ main ]
    paths:
      - "code/**"
      - "infra/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ main ]
    paths:
      - "code/**"
      - "infra/**"
      - ".github/workflows/**"

env:
  DEV_ENVIRONMENT_NAME: "dev"  # Update to '{devEnvironmentName}'

jobs:
  validation_dev:
    uses: ${{ github.repository }}/.github/workflows/templates/validation.yml@${{github.sha}}
    name: "Validation of IaC templates - Dev"
    with:
      environment: ${{ env.DEV_ENVIRONMENT_NAME }}
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
  
  deployment_dev:
    uses: ${{ github.repository }}/.github/workflows/templates/deployment.yml@${{github.sha}}
    name: "Deployment of IaC templates - Dev"
    needs: [ validation_dev ]
    if: github.event_name == 'push'
    with:
      environment: ${{ env.DEV_ENVIRONMENT_NAME }}
    secrets:
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      azure_location_name: ${{ secrets.AZURE_LOCATION }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
